/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xresloader_core_data_dst_CppDll */

#ifndef _Included_org_xresloader_core_data_dst_CppDll
#define _Included_org_xresloader_core_data_dst_CppDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xresloader_core_data_dst_CppDll
 * Method:    init_cpp_dll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xresloader_core_data_dst_CppDll_init_1cpp_1dll
  (JNIEnv *, jobject);

/*
 * Class:     org_xresloader_core_data_dst_CppDll
 * Method:    do_lua_string
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xresloader_core_data_dst_CppDll_do_1lua_1string
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
